# Generated by Django 4.1 on 2022-08-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='dni',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dni'),
        ),
    ]
