# Generated by Django 4.1 on 2022-08-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_pacient_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='dni',
            field=models.CharField(max_length=100, null=True, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='lastName',
            field=models.CharField(max_length=100, null=True, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
