# Generated by Django 4.1 on 2022-08-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_pacient_dni_alter_pacient_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
