# Generated by Django 4.1 on 2022-08-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_pacient_lastname_alter_pacient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='dni',
            field=models.CharField(default=1, max_length=100, verbose_name='Dni'),
            preserve_default=False,
        ),
    ]
