# Generated by Django 4.1 on 2022-08-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_doctor_lastname_alter_pacient_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
